### ISSUE TITLE
Missing instructions regarding requirements

### ISSUE THREAD

**Issue by robertklep** [marconfus/ha-nefit-ng#7]
I'm using a fresh HA setup (0.87.1) on Hassbian, and had to install some additional requirements to get the Nefit component up and running:
- `sudo apt-get install libxslt-dev`
- `pip install lxml` (as user `homeassistant`, with virtual environment activated)

But after that, it's working 👍🏻

**Comment by marconfus** [comment]
Oops, yes. There is a strange problem with the XMPP framework since HA 0.87
https://github.com/marconfus/ha-nefit-ng/issues/6
Unfortunately I only found a solution in patching the slixmpp library and using lxml instead of the native xml lib.
As I seem to be the only one whos setup triggers the problem I should create a different branch with the lxml dependency...

**Comment by marconfus** [comment]
I have removed my fork of slixmpp from the requirements. It's possible that you have to remove the package from your virtual env so that the original one get's installed again.

**Comment by robertklep** [comment]
Nah, it works for me now so not going to bother ;)
